services:
  test:
    build: .
    command: python3 /darknet/assets/darknet.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./assets:/darknet/assets